"""Add columns catalogue_num, cluster, created_at, updated_at

Revision ID: 764a6b028e27
Revises: e0d0f8836311
Create Date: 2025-02-01 16:42:54.312385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764a6b028e27'
down_revision: Union[str, None] = 'e0d0f8836311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cluster', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('images', 'catalog_num',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('images', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'items',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'registration_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('images', 'typology',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'author_lastname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'author_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'author_patronymic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'date_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('images', 'key_words',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'images', ['catalog_num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # Удаляем первичный ключ (если нужно откатить изменения)
    op.drop_constraint('pk_images', 'images', type_='primary')
    
    # Возвращаем тип catalog_num
    op.alter_column('images', 'catalog_num',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    
    # Удаляем столбцы cluster, created_at и updated_at
    op.drop_column('images', 'cluster')
    op.drop_column('images', 'created_at')
    op.drop_column('images', 'updated_at')
    
    # Возвращаем исходные типы столбцов
    op.alter_column('images', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'items',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'registration_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'typology',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'author_lastname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'author_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'author_patronymic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'date_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'key_words',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
