"""Drop index

Revision ID: d1e4cc623539
Revises: 2cc0100cdf9e
Create Date: 2025-02-04 12:07:13.520618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e4cc623539'
down_revision: Union[str, None] = '2cc0100cdf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
